### ISSUE TITLE
Disconnect Bug.

### ISSUE THREAD

**Issue by take99** [JacobFischer/sync-socket#1]
not good at English.
Leave the problem and fix code.
It is a really useful module.
But it took time to understand the manual.
It would be great if only a very simple example.

Bug
SyncSocket.prototype.disconnect = function() {
    this.destroyed = true;
    this.requester.kill();
    this.requester.request("disconnect");
};
fixed
SyncSocket.prototype.disconnect = function() {
    this.destroyed = true;
    this.requester.request("disconnect");
    this.requester.kill();
};

**Comment by JacobFischer** [comment]
Thanks for the heads up!

I fixed this in the latest version published to npm (v1.1.0).
